#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.


subdomain () {
	if [ $# -eq 2 ]
	then
	    domain=$2.$1
	    ip=$(dig ${domain} | awk "/^$domain/ { print \$4 \$5 }")
	    echo "The subdomain $2 is a ${ip:0:1} record and points to ${ip:1}"
	else
	    sub=( "www" "lb-01" "web-01" "web-02" )
	    for i in 0 1 2 3; do
		domain="${sub[i]}.$1"
		ip=$(dig ${domain} | awk "/^${domain}/ { print \$4 \$5 }")
		echo "The subdomain ${sub[i]} is a ${ip:0:1} record and points to ${ip:1}"
	    done
	fi
}
subdomain $1 $2
