#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get update
sudo apt-get -y install haproxy=2.6.\*
echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   frontend http
   bind *:80
   mode http
   default_backend servers

   backend servers
   balance roundrobin
   server 98914-web-01 107.21.16.201:80 check
   server 98914-web-02 100.25.169.239:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
