#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt-get -y update
sudo apt-get -y install haproxy
echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   frontend http
   bind *:80
   mode http
   default_backend servers

   backend servers
   balance roundrobin
   server 98914-web-01 107.21.16.201:80 check
   server 98914-web-02 100.25.169.239:80 check
" >> /etc/haproxy/haproxy.cfg

sudo /etc/init.d/haproxy restart
